### ISSUE TITLE
pointer error when trying to pass a FireDac DataSet from a MarsDataResource

### ISSUE THREAD

**Issue by jeanvdr** [andrea-magni/MARS#17]
This is working with sources from october 29 but not with those from december 3 (message returning by server: 'internal pointer error'):
type
  [Path('/maindata')]
  TMainDataResource = class(TMARSFDDataModuleResource)
    FDConnection1: TFDConnection;
    FDGUIxWaitCursor1: TFDGUIxWaitCursor;
    oneEmployee: TFDQuery;
    allEmployee: TFDQuery;
    country: TFDQuery;
    sales: TFDQuery;
  private
  protected
    [Context]
    FD: TMarsFireDac;
  public
    [GET, Path('/employee'), Produces(TMediaType.APPLICATION_JSON_FIREDAC)]
    function oneEmployeeQuery: TFDDataSet;
  end;

implementation
{%CLASSGROUP 'Vcl.Controls.TControl'}
{$R *.dfm}

uses
  MARS.Core.Registry;

{ TMainDataResource }
function TMainDataResource.oneEmployeeQuery: TFDDataSet;
begin
  FD.InjectMacroValues(TFDAdaptedDataSet(oneemployee).Command);
  FD.InjectParamValues(TFDAdaptedDataSet(oneemployee).Command);
  Result := oneEmployee;
end;

**Comment by andrea-magni** [comment]
Hi, as I wrote [here](https://plus.google.com/110715653341624212681/posts/gQGw8AHmYtv), you need to add the IsReference attribute to your method.
This is because I recently fixed a bug in MARS (about the time the Context is freed and this made me aware of another wrong situation: if you return a reference to a dataset on the resource datamodule, it will be freed two times [once when the return value is processed and sent to the client and a second time when the resource datamodule is freed, given it is still the owner of the dataset]. 

Please update the signature of your method as follow, and everything should work:

[GET, Path('/employee'), Produces(TMediaType.APPLICATION_JSON_FIREDAC), IsReference]
    function oneEmployeeQuery: TFDDataSe>; 

Please let me know and close the issue if everything is OK.

Thanks

**Comment by jeanvdr** [comment]
Everything works like a charm
Thanks a lot

Jean
