### ISSUE TITLE
TMARSClient Async AuthEndorsement

### ISSUE THREAD

**Issue by littleearth** [andrea-magni/MARS#21]
Hi,

Using Async calls when AuthEndorsement set to cookie (default) will not correctly authenticate.

So 2 suggestions:

1.) Add   LClient.AuthEndorsement := TMARSAuthEndorsement.AuthorizationBearer; to all Async calls

2.) Perform a check of AuthEndorsement and raise an exception if set to cookies to help with usage?

Also, thanks for this library; it's fantastic

**Comment by andrea-magni** [comment]
Hi, I never noticed that AuthEndorsement = Cookie was broken when used with Async calls!
Thanks for pointing this out. 
Cookie endorsement is most often used with web applications (while I tend to use AuthorizationBearer with Delphi client apps) so I never got (nor I would have never run) into this :-)

The problem was in order to make multiple async calls the http client is cloned for each async call and cookies were not copied from the original client (the one you used to authenticate). Now I have fixed this and everything seems to work on my side. Please double check if this solves your problems too and please let me know!

The significant commit is this one: https://github.com/andrea-magni/MARS/commit/ec31f30149d884b7f61f3702b5b624063ae3631a

Thanks also for the kind words about the library!

**Comment by littleearth** [comment]
That fixes it; thanks
