### ISSUE TITLE
Linux demos don't compiles

### ISSUE THREAD

**Issue by bobprog72** [andrea-magni/MARS#24]
i've created a new project with MarsCMD and the LinuxDaemon and Apache Module don't compile with "web.Multireq not found" error. (in mars.cors.attributes)

I commented the unit and all it's ok.
TIA
Bob

**Comment by andrea-magni** [comment]
Web.ReqMult.pas is an Embarcadero's unit that registers a parser for multipart form data (on the server side). It is required if you need to receive a multipart/form-data request from clients (MARS correctly handles content for you).
The problem is that unit has not been distributed for all platforms by Embarcadero so the compiler is looking for a dcu it cannot find. If you have Web.ReqMulti.pas somewhere (for example if you have Enterprise edition of Delphi) you may want to copy that pas to your project folder and everything will go smoothly.

Which Delphi version are you using? See also https://quality.embarcadero.com/browse/RSP-17216

Sincerely
